//! Proof Verification Engine
//!
//! This module provides automated proof verification capabilities by interfacing
//! with Lean's kernel and utilizing mathlib4 theorems. It supports both
//! synchronous and asynchronous verification with sophisticated caching.

use std::collections::{HashMap, VecDeque};
use std::sync::Arc;
use std::time::{Duration, Instant};

use dashmap::DashMap;
use parking_lot::RwLock;
use tokio::sync::{mpsc, oneshot, Semaphore};
use tokio::time::timeout;
use thiserror::Error;
use serde::{Serialize, Deserialize};

use crate::lean::{LeanTerm, LeanName, LeanError, Result as LeanResult};
use crate::lean::mathlib::{TheoremDatabase, MathlibTheorem, SearchQuery};
use crate::lean::server::LeanServer;
use crate::lean::cache::VerificationCache;
use crate::core::Term;

/// Verification-specific errors
#[derive(Error, Debug)]
pub enum VerificationError {
    #[error("Proof verification failed: {reason}")]
    VerificationFailed { reason: String },

    #[error("Verification timeout after {duration_ms}ms")]
    Timeout { duration_ms: u64 },

    #[error("Lean server unavailable")]
    ServerUnavailable,

    #[error("Invalid proof term: {reason}")]
    InvalidProof { reason: String },

    #[error("Missing dependency: {theorem}")]
    MissingDependency { theorem: String },

    #[error("Resource exhausted: {resource}")]
    ResourceExhausted { resource: String },

    #[error("Lean error: {0}")]
    Lean(#[from] LeanError),

    #[error("IO error: {0}")]
    Io(#[from] std::io::Error),
}

pub type VerificationResult<T> = std::result::Result<T, VerificationError>;

/// Result of proof verification
#[derive(Debug, Clone, Serialize, Deserialize)]
pub enum ProofResult {
    /// Proof is valid
    Valid {
        /// Optional proof term generated by Lean
        proof: Option<LeanTerm>,
        /// Time taken for verification
        time_ms: u128,
        /// Dependencies used in the proof
        dependencies: Vec<String>,
        /// Verification strategy used
        strategy: VerificationStrategy,
    },

    /// Proof is invalid
    Invalid {
        /// Error message from Lean
        error: String,
        /// Line number if applicable
        line: Option<u32>,
        /// Column number if applicable
        column: Option<u32>,
    },

    /// Verification timed out
    Timeout {
        /// Duration before timeout
        duration_ms: u64,
    },

    /// Could not determine validity
    Unknown {
        /// Reason for indeterminate result
        reason: String,
    },
}

impl ProofResult {
    /// Check if the result indicates a valid proof
    pub fn is_valid(&self) -> bool {
        matches!(self, ProofResult::Valid { .. })
    }

    /// Check if the result indicates an invalid proof
    pub fn is_invalid(&self) -> bool {
        matches!(self, ProofResult::Invalid { .. })
    }

    /// Get the verification time if available
    pub fn verification_time(&self) -> Option<Duration> {
        match self {
            ProofResult::Valid { time_ms, .. } => Some(Duration::from_millis(*time_ms as u64)),
            ProofResult::Timeout { duration_ms } => Some(Duration::from_millis(*duration_ms)),
            _ => None,
        }
    }

    /// Get dependencies used in the proof
    pub fn dependencies(&self) -> Vec<String> {
        match self {
            ProofResult::Valid { dependencies, .. } => dependencies.clone(),
            _ => Vec::new(),
        }
    }
}

/// Verification strategies for different proof approaches
#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
pub enum VerificationStrategy {
    /// Direct kernel verification
    Kernel,

    /// Use simp tactic
    Simp,

    /// Use auto tactic
    Auto,

    /// Use library_search
    LibrarySearch,

    /// Custom tactic combination
    Custom(u32), // Strategy ID

    /// Hybrid approach combining multiple strategies
    Hybrid,
}

impl VerificationStrategy {
    /// Get timeout for this strategy
    pub fn timeout_ms(&self) -> u64 {
        match self {
            VerificationStrategy::Kernel => 5000,
            VerificationStrategy::Simp => 10000,
            VerificationStrategy::Auto => 30000,
            VerificationStrategy::LibrarySearch => 60000,
            VerificationStrategy::Custom(_) => 15000,
            VerificationStrategy::Hybrid => 45000,
        }
    }

    /// Get priority (lower = higher priority)
    pub fn priority(&self) -> u32 {
        match self {
            VerificationStrategy::Kernel => 1,
            VerificationStrategy::Simp => 2,
            VerificationStrategy::Auto => 3,
            VerificationStrategy::LibrarySearch => 4,
            VerificationStrategy::Custom(_) => 5,
            VerificationStrategy::Hybrid => 6,
        }
    }
}

/// Verification request
#[derive(Debug)]
pub struct VerificationRequest {
    /// Unique request ID
    pub id: u64,

    /// Goal to prove
    pub goal: LeanTerm,

    /// Optional proof hint
    pub proof_hint: Option<LeanTerm>,

    /// Context (available hypotheses)
    pub context: Vec<(LeanName, LeanTerm)>,

    /// Preferred verification strategies
    pub strategies: Vec<VerificationStrategy>,

    /// Maximum time to spend on verification
    pub timeout: Duration,

    /// Whether to use theorem database
    pub use_mathlib: bool,

    /// Response channel
    pub response: oneshot::Sender<ProofResult>,
}

/// Metrics for verification performance
#[derive(Debug, Default)]
pub struct VerificationMetrics {
    pub total_requests: std::sync::atomic::AtomicU64,
    pub successful_proofs: std::sync::atomic::AtomicU64,
    pub failed_proofs: std::sync::atomic::AtomicU64,
    pub timeouts: std::sync::atomic::AtomicU64,
    pub cache_hits: std::sync::atomic::AtomicU64,
    pub avg_verification_time_ms: std::sync::atomic::AtomicU64,
    pub strategy_usage: RwLock<HashMap<VerificationStrategy, u64>>,
}

impl VerificationMetrics {
    pub fn record_request(&self) {
        self.total_requests.fetch_add(1, std::sync::atomic::Ordering::Relaxed);
    }

    pub fn record_success(&self, duration: Duration, strategy: VerificationStrategy) {
        self.successful_proofs.fetch_add(1, std::sync::atomic::Ordering::Relaxed);
        self.update_avg_time(duration);
        self.update_strategy_usage(strategy);
    }

    pub fn record_failure(&self) {
        self.failed_proofs.fetch_add(1, std::sync::atomic::Ordering::Relaxed);
    }

    pub fn record_timeout(&self) {
        self.timeouts.fetch_add(1, std::sync::atomic::Ordering::Relaxed);
    }

    pub fn record_cache_hit(&self) {
        self.cache_hits.fetch_add(1, std::sync::atomic::Ordering::Relaxed);
    }

    fn update_avg_time(&self, duration: Duration) {
        let old_avg = self.avg_verification_time_ms.load(std::sync::atomic::Ordering::Relaxed);
        let total = self.successful_proofs.load(std::sync::atomic::Ordering::Relaxed);
        let new_avg = (old_avg * (total - 1) + duration.as_millis() as u64) / total;
        self.avg_verification_time_ms.store(new_avg, std::sync::atomic::Ordering::Relaxed);
    }

    fn update_strategy_usage(&self, strategy: VerificationStrategy) {
        let mut usage = self.strategy_usage.write();
        *usage.entry(strategy).or_insert(0) += 1;
    }

    pub fn success_rate(&self) -> f64 {
        let total = self.total_requests.load(std::sync::atomic::Ordering::Relaxed);
        let success = self.successful_proofs.load(std::sync::atomic::Ordering::Relaxed);
        if total > 0 {
            success as f64 / total as f64
        } else {
            0.0
        }
    }

    pub fn cache_hit_rate(&self) -> f64 {
        let total = self.total_requests.load(std::sync::atomic::Ordering::Relaxed);
        let hits = self.cache_hits.load(std::sync::atomic::Ordering::Relaxed);
        if total > 0 {
            hits as f64 / total as f64
        } else {
            0.0
        }
    }
}

/// Main verification engine
pub struct LeanVerifier {
    /// Lean server for kernel operations
    server: Arc<LeanServer>,

    /// Mathlib theorem database
    theorem_db: Arc<TheoremDatabase>,

    /// Verification cache
    cache: Arc<VerificationCache>,

    /// Request queue
    request_queue: mpsc::UnboundedSender<VerificationRequest>,

    /// Performance metrics
    metrics: Arc<VerificationMetrics>,

    /// Configuration
    config: VerificationConfig,

    /// Concurrency control
    semaphore: Arc<Semaphore>,

    /// Request ID counter
    request_counter: std::sync::atomic::AtomicU64,
}

/// Configuration for the verification engine
#[derive(Debug, Clone)]
pub struct VerificationConfig {
    /// Maximum concurrent verifications
    pub max_concurrent: usize,

    /// Default timeout for verification
    pub default_timeout: Duration,

    /// Whether to use aggressive caching
    pub aggressive_caching: bool,

    /// Whether to use parallel strategy execution
    pub parallel_strategies: bool,

    /// Maximum proof search depth
    pub max_search_depth: u32,

    /// Whether to enable proof mining
    pub enable_proof_mining: bool,
}

impl Default for VerificationConfig {
    fn default() -> Self {
        Self {
            max_concurrent: num_cpus::get(),
            default_timeout: Duration::from_secs(30),
            aggressive_caching: true,
            parallel_strategies: true,
            max_search_depth: 10,
            enable_proof_mining: true,
        }
    }
}

impl LeanVerifier {
    /// Create a new verification engine
    pub async fn new(
        server: Arc<LeanServer>,
        theorem_db: Arc<TheoremDatabase>,
        cache: Arc<VerificationCache>,
        config: VerificationConfig,
    ) -> VerificationResult<Self> {
        let (request_tx, mut request_rx) = mpsc::unbounded_channel();
        let metrics = Arc::new(VerificationMetrics::default());
        let semaphore = Arc::new(Semaphore::new(config.max_concurrent));

        let verifier = Self {
            server: server.clone(),
            theorem_db: theorem_db.clone(),
            cache: cache.clone(),
            request_queue: request_tx,
            metrics: metrics.clone(),
            config: config.clone(),
            semaphore: semaphore.clone(),
            request_counter: std::sync::atomic::AtomicU64::new(0),
        };

        // Start request processing task
        let server_clone = server.clone();
        let theorem_db_clone = theorem_db.clone();
        let cache_clone = cache.clone();
        let metrics_clone = metrics.clone();
        let config_clone = config.clone();
        let semaphore_clone = semaphore.clone();

        tokio::spawn(async move {
            while let Some(request) = request_rx.recv().await {
                let server = server_clone.clone();
                let theorem_db = theorem_db_clone.clone();
                let cache = cache_clone.clone();
                let metrics = metrics_clone.clone();
                let config = config_clone.clone();
                let semaphore = semaphore_clone.clone();

                tokio::spawn(async move {
                    let _permit = semaphore.acquire().await.unwrap();
                    let result = Self::process_verification_request(
                        request,
                        server,
                        theorem_db,
                        cache,
                        metrics,
                        config,
                    ).await;

                    // Response is sent within process_verification_request
                    drop(result);
                });
            }
        });

        Ok(verifier)
    }

    /// Verify a goal with optional proof hint
    pub async fn verify(&self, goal: LeanTerm, proof_hint: Option<LeanTerm>) -> VerificationResult<ProofResult> {
        self.verify_with_context(goal, proof_hint, Vec::new()).await
    }

    /// Verify a goal with context and proof hint
    pub async fn verify_with_context(
        &self,
        goal: LeanTerm,
        proof_hint: Option<LeanTerm>,
        context: Vec<(LeanName, LeanTerm)>,
    ) -> VerificationResult<ProofResult> {
        let request_id = self.request_counter.fetch_add(1, std::sync::atomic::Ordering::Relaxed);
        let (response_tx, response_rx) = oneshot::channel();

        let request = VerificationRequest {
            id: request_id,
            goal,
            proof_hint,
            context,
            strategies: vec![
                VerificationStrategy::Kernel,
                VerificationStrategy::Simp,
                VerificationStrategy::Auto,
                VerificationStrategy::LibrarySearch,
            ],
            timeout: self.config.default_timeout,
            use_mathlib: true,
            response: response_tx,
        };

        self.request_queue.send(request)
            .map_err(|_| VerificationError::ServerUnavailable)?;

        response_rx.await
            .map_err(|_| VerificationError::ServerUnavailable)
    }

    /// Find and apply relevant theorems to a goal
    pub async fn find_applicable_theorems(&self, goal: &LeanTerm) -> Vec<MathlibTheorem> {
        self.theorem_db.find_applicable(goal)
    }

    /// Attempt automated proof using various strategies
    pub async fn attempt_auto_proof(&self, goal: LeanTerm) -> VerificationResult<ProofResult> {
        let strategies = vec![
            VerificationStrategy::Simp,
            VerificationStrategy::Auto,
            VerificationStrategy::LibrarySearch,
        ];

        for strategy in strategies {
            match self.verify_with_strategy(goal.clone(), None, strategy).await {
                Ok(result) if result.is_valid() => return Ok(result),
                _ => continue,
            }
        }

        Ok(ProofResult::Unknown {
            reason: "No automated strategy succeeded".to_string(),
        })
    }

    /// Verify using a specific strategy
    async fn verify_with_strategy(
        &self,
        goal: LeanTerm,
        proof_hint: Option<LeanTerm>,
        strategy: VerificationStrategy,
    ) -> VerificationResult<ProofResult> {
        let start = Instant::now();

        // Check cache first
        let cache_key = (goal.clone(), proof_hint.clone(), strategy);
        if let Some(cached_result) = self.cache.get_verification(&cache_key).await {
            self.metrics.record_cache_hit();
            return Ok(cached_result);
        }

        let result = match strategy {
            VerificationStrategy::Kernel => self.verify_kernel(goal.clone()).await,
            VerificationStrategy::Simp => self.verify_simp(goal.clone()).await,
            VerificationStrategy::Auto => self.verify_auto(goal.clone()).await,
            VerificationStrategy::LibrarySearch => self.verify_library_search(goal.clone()).await,
            VerificationStrategy::Custom(id) => self.verify_custom(goal.clone(), id).await,
            VerificationStrategy::Hybrid => self.verify_hybrid(goal.clone()).await,
        };

        let duration = start.elapsed();

        match &result {
            Ok(ProofResult::Valid { .. }) => {
                self.metrics.record_success(duration, strategy);
                // Cache successful results
                self.cache.store_verification(cache_key, result.as_ref().unwrap().clone()).await;
            }
            Ok(ProofResult::Invalid { .. }) => {
                self.metrics.record_failure();
            }
            Ok(ProofResult::Timeout { .. }) => {
                self.metrics.record_timeout();
            }
            _ => {}
        }

        result
    }

    /// Verify using Lean's kernel directly
    async fn verify_kernel(&self, goal: LeanTerm) -> VerificationResult<ProofResult> {
        let start = Instant::now();

        match timeout(
            Duration::from_millis(VerificationStrategy::Kernel.timeout_ms()),
            self.server.type_check(goal)
        ).await {
            Ok(Ok(_)) => Ok(ProofResult::Valid {
                proof: None,
                time_ms: start.elapsed().as_millis(),
                dependencies: Vec::new(),
                strategy: VerificationStrategy::Kernel,
            }),
            Ok(Err(e)) => Ok(ProofResult::Invalid {
                error: e.to_string(),
                line: None,
                column: None,
            }),
            Err(_) => Ok(ProofResult::Timeout {
                duration_ms: VerificationStrategy::Kernel.timeout_ms(),
            }),
        }
    }

    /// Verify using simp tactic
    async fn verify_simp(&self, goal: LeanTerm) -> VerificationResult<ProofResult> {
        let start = Instant::now();
        let tactic = "simp".to_string();

        match timeout(
            Duration::from_millis(VerificationStrategy::Simp.timeout_ms()),
            self.server.apply_tactic(goal, tactic)
        ).await {
            Ok(Ok(proof)) => Ok(ProofResult::Valid {
                proof: Some(proof),
                time_ms: start.elapsed().as_millis(),
                dependencies: Vec::new(), // TODO: Extract from proof term
                strategy: VerificationStrategy::Simp,
            }),
            Ok(Err(e)) => Ok(ProofResult::Invalid {
                error: e.to_string(),
                line: None,
                column: None,
            }),
            Err(_) => Ok(ProofResult::Timeout {
                duration_ms: VerificationStrategy::Simp.timeout_ms(),
            }),
        }
    }

    /// Verify using auto tactic
    async fn verify_auto(&self, goal: LeanTerm) -> VerificationResult<ProofResult> {
        let start = Instant::now();
        let tactic = "auto".to_string();

        match timeout(
            Duration::from_millis(VerificationStrategy::Auto.timeout_ms()),
            self.server.apply_tactic(goal, tactic)
        ).await {
            Ok(Ok(proof)) => Ok(ProofResult::Valid {
                proof: Some(proof),
                time_ms: start.elapsed().as_millis(),
                dependencies: Vec::new(), // TODO: Extract from proof term
                strategy: VerificationStrategy::Auto,
            }),
            Ok(Err(e)) => Ok(ProofResult::Invalid {
                error: e.to_string(),
                line: None,
                column: None,
            }),
            Err(_) => Ok(ProofResult::Timeout {
                duration_ms: VerificationStrategy::Auto.timeout_ms(),
            }),
        }
    }

    /// Verify using library_search
    async fn verify_library_search(&self, goal: LeanTerm) -> VerificationResult<ProofResult> {
        let start = Instant::now();

        // First, find applicable theorems
        let applicable_theorems = self.find_applicable_theorems(&goal).await;

        if applicable_theorems.is_empty() {
            return Ok(ProofResult::Invalid {
                error: "No applicable theorems found".to_string(),
                line: None,
                column: None,
            });
        }

        // Try applying each theorem
        for theorem in applicable_theorems.iter().take(5) { // Limit search
            let application = format!("exact {}", theorem.name);

            match timeout(
                Duration::from_millis(5000), // Shorter timeout per theorem
                self.server.apply_tactic(goal.clone(), application)
            ).await {
                Ok(Ok(proof)) => {
                    return Ok(ProofResult::Valid {
                        proof: Some(proof),
                        time_ms: start.elapsed().as_millis(),
                        dependencies: vec![theorem.name.clone()],
                        strategy: VerificationStrategy::LibrarySearch,
                    });
                }
                _ => continue,
            }
        }

        Ok(ProofResult::Invalid {
            error: "Library search failed to find applicable proof".to_string(),
            line: None,
            column: None,
        })
    }

    /// Verify using custom strategy
    async fn verify_custom(&self, goal: LeanTerm, strategy_id: u32) -> VerificationResult<ProofResult> {
        // TODO: Implement custom strategies
        Ok(ProofResult::Unknown {
            reason: format!("Custom strategy {} not implemented", strategy_id),
        })
    }

    /// Verify using hybrid approach
    async fn verify_hybrid(&self, goal: LeanTerm) -> VerificationResult<ProofResult> {
        // Try strategies in parallel if enabled
        if self.config.parallel_strategies {
            self.verify_parallel(goal).await
        } else {
            self.verify_sequential(goal).await
        }
    }

    /// Verify using parallel strategy execution
    async fn verify_parallel(&self, goal: LeanTerm) -> VerificationResult<ProofResult> {
        let strategies = vec![
            VerificationStrategy::Simp,
            VerificationStrategy::Auto,
            VerificationStrategy::LibrarySearch,
        ];

        let mut handles = Vec::new();

        for strategy in strategies {
            let goal_clone = goal.clone();
            let self_clone = self.clone_for_parallel();

            let handle = tokio::spawn(async move {
                self_clone.verify_with_strategy(goal_clone, None, strategy).await
            });

            handles.push(handle);
        }

        // Wait for first successful result
        for handle in handles {
            if let Ok(Ok(result)) = handle.await {
                if result.is_valid() {
                    return Ok(result);
                }
            }
        }

        Ok(ProofResult::Unknown {
            reason: "All parallel strategies failed".to_string(),
        })
    }

    /// Verify using sequential strategy execution
    async fn verify_sequential(&self, goal: LeanTerm) -> VerificationResult<ProofResult> {
        let strategies = vec![
            VerificationStrategy::Simp,
            VerificationStrategy::Auto,
            VerificationStrategy::LibrarySearch,
        ];

        for strategy in strategies {
            match self.verify_with_strategy(goal.clone(), None, strategy).await {
                Ok(result) if result.is_valid() => return Ok(result),
                _ => continue,
            }
        }

        Ok(ProofResult::Unknown {
            reason: "All sequential strategies failed".to_string(),
        })
    }

    /// Process a verification request
    async fn process_verification_request(
        request: VerificationRequest,
        server: Arc<LeanServer>,
        theorem_db: Arc<TheoremDatabase>,
        cache: Arc<VerificationCache>,
        metrics: Arc<VerificationMetrics>,
        config: VerificationConfig,
    ) {
        metrics.record_request();

        // Create temporary verifier instance for this request
        let (dummy_tx, _) = mpsc::unbounded_channel();
        let verifier = LeanVerifier {
            server,
            theorem_db,
            cache,
            request_queue: dummy_tx,
            metrics: metrics.clone(),
            config,
            semaphore: Arc::new(Semaphore::new(1)),
            request_counter: std::sync::atomic::AtomicU64::new(0),
        };

        let result = match timeout(
            request.timeout,
            verifier.verify_with_context(request.goal, request.proof_hint, request.context)
        ).await {
            Ok(Ok(result)) => result,
            Ok(Err(e)) => ProofResult::Invalid {
                error: e.to_string(),
                line: None,
                column: None,
            },
            Err(_) => ProofResult::Timeout {
                duration_ms: request.timeout.as_millis() as u64,
            },
        };

        let _ = request.response.send(result);
    }

    /// Clone for parallel execution (stub implementation)
    fn clone_for_parallel(&self) -> Self {
        // This is a simplified clone for demonstration
        // In practice, you'd want to share the expensive components
        Self {
            server: self.server.clone(),
            theorem_db: self.theorem_db.clone(),
            cache: self.cache.clone(),
            request_queue: self.request_queue.clone(),
            metrics: self.metrics.clone(),
            config: self.config.clone(),
            semaphore: self.semaphore.clone(),
            request_counter: std::sync::atomic::AtomicU64::new(0),
        }
    }

    /// Get verification metrics
    pub fn metrics(&self) -> &VerificationMetrics {
        &self.metrics
    }

    /// Get configuration
    pub fn config(&self) -> &VerificationConfig {
        &self.config
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::lean::{LeanLevel, LeanTerm};

    #[test]
    fn test_verification_strategy_properties() {
        assert_eq!(VerificationStrategy::Kernel.priority(), 1);
        assert_eq!(VerificationStrategy::Simp.priority(), 2);
        assert!(VerificationStrategy::Kernel.timeout_ms() < VerificationStrategy::Auto.timeout_ms());
    }

    #[test]
    fn test_proof_result_validity() {
        let valid_result = ProofResult::Valid {
            proof: None,
            time_ms: 100,
            dependencies: Vec::new(),
            strategy: VerificationStrategy::Kernel,
        };

        assert!(valid_result.is_valid());
        assert!(!valid_result.is_invalid());
        assert_eq!(valid_result.verification_time(), Some(Duration::from_millis(100)));
    }

    #[test]
    fn test_verification_config_defaults() {
        let config = VerificationConfig::default();
        assert!(config.max_concurrent > 0);
        assert!(config.default_timeout.as_secs() > 0);
        assert!(config.aggressive_caching);
    }

    #[test]
    fn test_verification_metrics() {
        let metrics = VerificationMetrics::default();
        metrics.record_request();
        metrics.record_success(Duration::from_millis(100), VerificationStrategy::Simp);

        assert_eq!(metrics.total_requests.load(std::sync::atomic::Ordering::Relaxed), 1);
        assert_eq!(metrics.successful_proofs.load(std::sync::atomic::Ordering::Relaxed), 1);
        assert_eq!(metrics.success_rate(), 1.0);
    }
}